import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // تأكد من استيراد ملف CSS
import Navbar from "../app/Navbar/page";
import Footer from "./Footer/page";
import TimeContextProvider from "./context/tiemContext";
import QuranContextProvider from "./context/quranContext";
import TafsirContextProvider from './context/tafsirContext';
import AdkarContextProvider from "./context/adhkarContect";
import RadioContextProvider from "./context/radioContext";
import HadithsContextProvider from './context/hadithsContext';
import { ThemeModeScript } from "flowbite-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Islamic App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <HadithsContextProvider>
          <RadioContextProvider>
            <AdkarContextProvider>
              <TafsirContextProvider>
                <QuranContextProvider>
                  <TimeContextProvider>
                    <Navbar />
                    <main className="flex-grow bg-white dark:bg-gray-900">{children}</main>
                    <Footer />
                  </TimeContextProvider>
                </QuranContextProvider>
              </TafsirContextProvider>
            </AdkarContextProvider>
          </RadioContextProvider>
        </HadithsContextProvider>
      </body>
    </html>
  );
}
